export const DOG_BREEDS = [
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Bully",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Belgian Malinois",
  "Belgian Tervuren",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "Brittany",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chinese Crested",
  "Chow Chow",
  "Cocker Spaniel",
  "Collie",
  "Corgi (Pembroke Welsh)",
  "Corgi (Cardigan Welsh)",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dutch Shepherd",
  "English Setter",
  "English Springer Spaniel",
  "Fox Terrier",
  "French Bulldog",
  "German Shepherd",
  "German Shorthaired Pointer",
  "Giant Schnauzer",
  "Golden Retriever",
  "Great Dane",
  "Great Pyrenees",
  "Greyhound",
  "Havanese",
  "Husky (Siberian)",
  "Irish Setter",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Labrador Retriever",
  "Lhasa Apso",
  "Maltese",
  "Mastiff",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Old English Sheepdog",
  "Papillon",
  "Pekingese",
  "Pointer",
  "Pomeranian",
  "Poodle (Standard)",
  "Poodle (Miniature)",
  "Poodle (Toy)",
  "Portuguese Water Dog",
  "Pug",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Scottish Terrier",
  "Shar Pei",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Staffordshire Bull Terrier",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
  "Mixed Breed",
  "Other"
];
